workflows:
  flutter-build:
    name: Build Flutter App
    working_directory: passwords_manager
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
        CERTIFICATE_PRIVATE_KEY: Encrypted(...)
        CERTIFICATE_PASSWORD: Encrypted(...)
        PROVISIONING_PROFILE: Encrypted(...)

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ios/Pods
        - ios/.symlinks
        - .packages
        - build/

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          flutter build apk --release

      - name: Build signed iOS IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - khadidjadrf@gmail.com
