workflows:
  flutter-build:
    name: Build Flutter App
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ios/Pods
        - ios/.symlinks
        - .packages
        - build/

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          flutter build apk --release

      - name: Build iOS App (unsigned)
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - khadidjadrf@gmail.com
