name: passwords_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  android_intent_plus: ^5.3.0
  local_auth: ^2.3.0
  shared_preferences: ^2.5.2  
  loading_indicator: ^3.1.1
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  sqflite_common_ffi_web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcherIcon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: BabasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
